version: 0.2

env:
  variables:
    IMAGE_TAG: latest
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - BACKEND_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/autoblog-backend
      - FRONTEND_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/autoblog-frontend

  build:
    commands:
      - echo Building backend...
      - cd backend
      - docker build -t $BACKEND_URI:$IMAGE_TAG .
      - cd ..
      - echo Building frontend...
      - cd frontend
      - docker build -t $FRONTEND_URI:$IMAGE_TAG .
      - cd ..

  post_build:
    commands:
      - echo Pushing images...
      - docker push $BACKEND_URI:$IMAGE_TAG
      - docker push $FRONTEND_URI:$IMAGE_TAG

artifacts:
  files: []

